import io
import math
from datetime import datetime
from xml.sax.saxutils import escape

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from sqlalchemy.orm import Session

from app import models
from app.services.results import recommend, session_rows, summarize

def _fmt(v):
    return "-" if v is None else str(v)

def _radar_png(scores: dict) -> io.BytesIO:
    labels = list(scores)
    values = [scores[k] for k in labels]
    angles = [i / len(labels) * 2 * math.pi for i in range(len(labels))]
    values += values[:1]
    angles += angles[:1]
    fig, ax = plt.subplots(figsize=(4, 4), subplot_kw={"polar": True})
    ax.plot(angles, values, linewidth=2)
    ax.fill(angles, values, alpha=0.25)
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels([k.replace("_", " ") for k in labels], fontsize=8)
    ax.set_ylim(0, 10)
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return buf

def generate_pdf(db: Session, session_id: int) -> bytes:
    session = db.get(models.InterviewSession, session_id)
    candidate = db.get(models.Candidate, session.candidate_id)
    interview = db.get(models.Interview, session.interview_id)
    rows = session_rows(db, session_id)
    overall, radar = summarize(rows)
    rec = recommend(overall)

    styles = getSampleStyleSheet()
    body = styles["BodyText"]
    story = [
        Paragraph("HireIQ Evaluation Report", styles["Title"]),
        Paragraph(f"<b>Candidate:</b> {escape(candidate.name)} ({escape(candidate.email)})", body),
        Paragraph(f"<b>Interview:</b> {escape(interview.title)}", body),
        Paragraph(f"<b>Generated:</b> {datetime.utcnow():%Y-%m-%d %H:%M} UTC", body),
        Spacer(1, 12),
        Paragraph(f"Overall score: {_fmt(overall)} / 100", styles["Heading2"]),
        Paragraph(f"Recommendation: {rec}", styles["Heading2"]),
    ]
    if len(radar) >= 3:
        story.append(Image(_radar_png(radar), width=9 * cm, height=9 * cm))

    data = [["#", "Question", "Score", "Confidence"]]
    for n, r in enumerate(rows, 1):
        data.append([str(n), Paragraph(escape(r["question"]), body), _fmt(r["score"]), _fmt(r["confidence"])])
    table = Table(data, colWidths=[1 * cm, 10 * cm, 2.5 * cm, 3 * cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story += [Spacer(1, 12), Paragraph("Per-question breakdown", styles["Heading2"]), table]

    for n, r in enumerate(rows, 1):
        story += [Spacer(1, 10), Paragraph(f"Q{n}. {escape(r['question'])}", styles["Heading3"])]
        crit = ", ".join(f"{k.replace('_', ' ')}: {v}" for k, v in (r["criteria_scores"] or {}).items())
        if crit:
            story.append(Paragraph(f"<b>Criteria (0-10):</b> {escape(crit)}", body))
        if r["feedback"]:
            story.append(Paragraph(f"<b>Feedback:</b> {escape(r['feedback'])}", body))
        story.append(Paragraph(f"<b>Sentiment:</b> {_fmt(r['sentiment'])}", body))
        story.append(Paragraph(f"<b>Transcript (verbatim):</b> {escape(r['transcript'] or '(none)')}", body))

    story += [Spacer(1, 16), Paragraph(
        "<i>This report was generated by an AI system to assist hiring decisions. It may contain "
        "errors or bias and must be reviewed by a human before any hiring decision is made.</i>", body)]

    buf = io.BytesIO()
    SimpleDocTemplate(buf, pagesize=A4, leftMargin=2 * cm, rightMargin=2 * cm).build(story)

    report = (db.query(models.Report).filter_by(session_id=session_id).first()
              or models.Report(session_id=session_id))
    report.overall_score = overall
    report.recommendation = rec
    db.add(report)
    db.commit()
    return buf.getvalue()